name: Keep Render App Alive

on:
  schedule:
    - cron: '*/14 * * * *' # Runs every 14 minutes
  workflow_dispatch: # Allows manual triggering
  
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -I https://karewar-gaurav.onrender.com/
